on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      #- uses: sebelino/action-dirname@latest
      - uses: actions/checkout@v3.0.2
      - uses: ./
        id: dirname
        with:
          files: '["main.tf", "versions.tf", "modules/vpc/sg.tf"]'
      - run: |
          echo "Output: ${{ steps.dirname.outputs.directories }}"
